### 회원가입(HOST)
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test1234!@#",
  "nickName": "Beemo",
  "phoneNumber": "010-1234-5678"
}

> {%
  // 응답 구조에 따라 수정 필요
  // 예: { "userId": 1, ... } 라면 아래처럼 유지
  client.global.set("userId", response.body.data.userId);
%}

### 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test1234!@#"
}

> {%
  client.global.set("accessToken", response.body.data.accessToken);
%}

### 1-1. 모임 이미지 선 업로드 (png / jpg 2장)
POST http://localhost:8080/api/v1/groups/images/upload?userId={{userId}}
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{accessToken}}

--boundary
Content-Disposition: form-data; name="images"; filename="img1.png"
Content-Type: image/png

< ../image/resources/img1.png
--boundary
Content-Disposition: form-data; name="images"; filename="img2.jpg"
Content-Type: image/jpeg

< ../image/resources/img2.jpg
--boundary--

> {%
  const images = response.body.data.images;

  client.global.set("img0_main",  images[0].imageUrl440x240);
  client.global.set("img0_thumb", images[0].imageUrl100x100);

  client.global.set("img1_main",  images[1].imageUrl440x240);
  client.global.set("img1_thumb", images[1].imageUrl100x100);
%}

### 1-2. 모임 생성 (png/jpg 업로드 결과 URL로 생성)
POST http://localhost:8080/api/v1/groups/create?userId={{userId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}


{
  "title": "강남에서 하는 자바 스터디 - PNG/JPG 테스트",
  "location": "서울 강남구",
  "locationDetail": "강남역 2번 출구 근처 카페",
  "startTime": "2025-12-10T19:00:00",
  "tags": [
    "자바",
    "백엔드",
    "스터디"
  ],
  "description": "PNG/JPG 업로드 후 URL을 이용해서 모임을 생성하는 테스트입니다.",
  "maxParticipants": 12,
  "images": [
    {
      "sortOrder": 0,
      "imageUrl440x240": "{{img0_main}}",
      "imageUrl100x100": "{{img0_thumb}}"
    },
    {
      "sortOrder": 1,
      "imageUrl440x240": "{{img1_main}}",
      "imageUrl100x100": "{{img1_thumb}}"
    }
  ]
}

> {%
  // 그룹 ID 저장 (응답 구조에 맞게 조정)
  client.global.set("groupId_png_jpg", response.body.data.id);
%}

### 회원가입(MEMBER 1)
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "Test1234!@#",
  "nickName": "Heemo",
  "phoneNumber": "010-1234-5678"
}

> {%
  // 응답 구조에 따라 수정 필요
  // 예: { "userId": 1, ... } 라면 아래처럼 유지
  client.global.set("memberId1", response.body.data.userId);
%}

### 로그인 (MEMBER 1)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "Test1234!@#"
}

> {%
  client.global.set("accessTokenByMember1", response.body.data.accessToken);
%}

### 모임 참여 (MEMBER 1)
POST http://localhost:8080/api/v1/groups/{{groupId_png_jpg}}/attend
    ?userId=2
Content-Type: application/json
Authorization: Bearer {{accessTokenByMember1}}

{

}

### 회원가입(MEMBER 2)
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "Test1234!@#",
  "nickName": "Qeemo",
  "phoneNumber": "010-1234-5678"
}

> {%
  // 응답 구조에 따라 수정 필요
  // 예: { "userId": 1, ... } 라면 아래처럼 유지
  client.global.set("memberId1", response.body.data.userId);
%}

### 로그인 (MEMBER 2)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "Test1234!@#"
}

> {%
  client.global.set("accessTokenByMember2", response.body.data.accessToken);
%}

### 모임 참여 (MEMBER 2)
POST http://localhost:8080/api/v1/groups/{{groupId_png_jpg}}/attend
    ?userId=3
Content-Type: application/json
Authorization: Bearer {{accessTokenByMember2}}

{

}

### 모임 취소 (MEMBER 1)
POST http://localhost:8080/api/v1/groups/{{groupId_png_jpg}}/cancel
    ?userId=2
Content-Type: application/json
Authorization: Bearer {{accessTokenByMember1}}

{

}