### 회원가입
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test1234!@#",
  "nickName": "Beemo",
  "phoneNumber": "010-1234-5678"
}

### 모임 생성
POST http://localhost:8080/api/v1/groups/create
    ?userId=1
Content-Type: application/json

{
  "title": "강남에서 하는 자바 스터디",
  "location": "서울 강남구",
  "locationDetail": "강남역 2번 출구 근처 카페",
  "startTime": "2025-12-10T19:00:00",
  "endTime": "2025-12-10T21:00:00",
  "tags": [
    "자바",
    "백엔드",
    "스터디"
  ],
  "description": "자바 백엔드 신입 준비하는 분들을 위한 스터디입니다.",
  "maxParticipants": 12
}

### 모임 이미지 생성
POST http://localhost:8080/api/v1/groups/images/1/upload
    ?userId=1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="img1.png"
Content-Type: image/png

< ../image/resources/img1.png
--boundary
Content-Disposition: form-data; name="images"; filename="img2.jpg"
Content-Type: image/jpeg

< ../image/resources/img2.jpg
--boundary--}