### 회원가입
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test1234!@#",
  "nickName": "Beemo",
  "phoneNumber": "010-1234-5678"
}

### 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test1234!@#"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
%}

### 보호된 API 요청 (테스트용)
GET http://localhost:8080/api/v1/user/test
Authorization: Bearer {{accessToken}}