### 회원가입
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test1234!@#",
  "nickName": "test"
}

### 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test1234!@#"
}

> {%
  client.global.set("accessToken", response.body.data.accessToken);
%}

### 유저 정보 조회
GET http://localhost:8080/api/v1/users/1
Authorization: Bearer {{accessToken}}

### 유저 프로필 이미지 변경
PATCH http://localhost:8080/api/v1/users/profile-image
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="file"; filename="img1.png"
Content-Type: image/png

< ../image/resources/img1.png
--Boundary--

### 유저 프로필 정보 변경 (JSON)
PATCH http://localhost:8080/api/v1/users/profile
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "nickName": "예은",
  "mbti": "ISTP",
  "profileMessage": "앙냥냥"
}

### 알림 설정 변경
PATCH http://localhost:8080/api/v1/users/notification?isNotificationEnabled=true
Authorization: Bearer {{accessToken}}


### 팔로우 테스트용 회원 추가
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email": "follower@example.com",
  "password": "Test1234!@#",
  "nickName": "팔로우 대상"
}

### 팔로우 요청
POST http://localhost:8080/api/v1/users/follow?followNickname=팔로우 대상
Authorization: Bearer {{accessToken}}

### 팔로우 취소
DELETE http://localhost:8080/api/v1/users/unfollow?unFollowNickname=예은
Authorization: Bearer {{accessToken}}

### 이메일 중복검사
GET http://localhost:8080/api/v1/users/email/availability

### 닉네임 중복검사
GET http://localhost:8080/api/v1/users/nickname/availability?nickname=test

### 팔로우 리스트 조회 (초기값)
GET http://localhost:8080/api/v1/users/1/follow?size=10

> {%
  client.global.set("nextCursor", response.body.data.nextCursor);
%}

### 팔로우 리스트 조회 (cursor)
GET http://localhost:8080/api/v1/users/1/follow?cursor={{nextCursor}}&size=10

> {%
  client.global.set("nextCursor", response.body.data.nextCursor);
%}