### 0. 회원가입(HOST)
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test1234!@#",
  "nickName": "Beemo",
  "phoneNumber": "010-1234-5678"
}

> {%
  client.global.set("userId", response.body.data.userId);
%}


### 0-1. HOST 로그인 - accessToken 발급
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test1234!@#"
}

> {%
  client.global.set("hostAccessToken", response.body.data.accessToken);
%}


### 1-1. 모임 V2 이미지 선 업로드 (png / jpg 2장) - imageKey 저장
POST http://localhost:8080/api/v2/groups/images/upload
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{hostAccessToken}}

--boundary
Content-Disposition: form-data; name="images"; filename="img1.png"
Content-Type: image/png

< ../../image/resources/img1.png
--boundary
Content-Disposition: form-data; name="images"; filename="img2.jpg"
Content-Type: image/jpeg

< ../../image/resources/img2.jpg
--boundary--

> {%
  const images = response.body.data.images;

  client.global.set("img0_key", images[0].imageKey);
  client.global.set("img1_key", images[1].imageKey);
%}


### 1-2. 모임 V2 생성 (정상 케이스: 기준일 2026-12-19 이후 날짜로 생성)
POST http://localhost:8080/api/v2/groups/create
Content-Type: application/json
Authorization: Bearer {{hostAccessToken}}

{
  "title": "강남에서 하는 자바 스터디 - PNG/JPG 테스트",
  "location": "서울 강남구",
  "joinPolicy": "INSTANT",
  "locationDetail": "강남역 2번 출구 근처 카페",
  "startTime": "2026-12-20T19:00:00",
  "endTime": "2026-12-20T21:00:00",
  "tags": [
    "자바",
    "백엔드",
    "스터디"
  ],
  "description": "PNG/JPG 업로드 후 imageKey를 이용해서 모임을 생성하는 테스트입니다.",
  "maxParticipants": 12,
  "images": [
    {
      "sortOrder": 0,
      "imageKey": "{{img0_key}}"
    },
    {
      "sortOrder": 1,
      "imageKey": "{{img1_key}}"
    }
  ]
}

> {%
  client.global.set("groupId", response.body.data.id);
%}


### 1-3. V2 로그인 후, 현재 유저 기준 참여 상태 포함하여 상세 조회
GET http://localhost:8080/api/v2/groups/{{groupId}}
Authorization: Bearer {{hostAccessToken}}


### 2-1. 예외발생: 모임 V2 생성 (Redis에 존재하지 않는 imageKey는 404 발생)
POST http://localhost:8080/api/v2/groups/create
Content-Type: application/json
Authorization: Bearer {{hostAccessToken}}

{
  "title": "강남에서 하는 자바 스터디 - 지난 날짜 예외 테스트",
  "location": "서울 강남구",
  "joinPolicy": "INSTANT",
  "locationDetail": "강남역 2번 출구 근처 카페",
  "startTime": "2026-12-10T19:00:00",
  "endTime": "2026-12-10T21:00:00",
  "tags": [
    "자바",
    "백엔드",
    "스터디"
  ],
  "description": "기준일(2026-12-19, Asia/Seoul)보다 과거 startTime이면 예외가 떠야 합니다.",
  "maxParticipants": 12,
  "images": [
    {
      "sortOrder": 0,
      "imageKey": "{{img0_key}}"
    },
    {
      "sortOrder": 1,
      "imageKey": "{{img1_key}}"
    }
  ]
}
