### 1. 단일 이미지 업로드 (원본)
POST http://localhost:8080/api/v1/images/original?dir=test
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="img3.jpeg"
Content-Type: image/jpeg

< ./resources/img3.jpeg
--boundary--


### 3. 여러 이미지 업로드 (원본)
POST http://localhost:8080/api/v1/images/originals?dir=test
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="files"; filename="img1.png"
Content-Type: image/png

< ./resources/img1.png
--boundary
Content-Disposition: form-data; name="files"; filename="img2.jpg"
Content-Type: image/jpeg

< ./resources/img2.jpg
--boundary--


### 2. 단일 이미지 업로드 (WebP 변환 저장)
POST http://localhost:8080/api/v1/images/webp?dir=test
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="any-image.jpg"
Content-Type: image/jpeg

< ./resources/test-webp2.webp
--boundary--


### 4. 여러 이미지 업로드 (모두 WebP 변환 저장)
POST http://localhost:8080/api/v1/images/webps?dir=test
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="files"; filename="img1.png"
Content-Type: image/png

< ./resources/img1.png
--boundary
Content-Disposition: form-data; name="files"; filename="img2.jpg"
Content-Type: image/jpeg

< ./resources/img2.jpg
--boundary
Content-Disposition: form-data; name="files"; filename="test-webp1.webp"
Content-Type: image/webp

< ./resources/test-webp2.webp
--boundary--


### 5. 한 개 이미지 삭제
# 업로드 응답에서 받은 key 사용
DELETE http://localhost:8080/api/v1/images/one
    ?key=test/20251206141745_0_1f6f3420-0e78-4a5e-b782-93834937c552.webp


### 6. 여러 개 이미지 삭제
DELETE http://localhost:8080/api/v1/images
    ?keys=test/20251206141808_0_51d58b84-080c-47d2-9ce0-4e50b2e00b63.png
    &keys=test/20251206141808_1_3dea121d-7d39-4e3d-8b02-3dce01a8a929.jpg

### 7. 단일 이미지 업로드 (썸네일 변환 저장)
POST http://localhost:8080/api/v1/images/thumb?dir=test
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="big-image.jpg"
Content-Type: image/jpeg

< ./test-webp2.webp
--boundary--

